import type { Metadata } from "next";
import philosopher from 'next/font/local';
import "./globals.css";
import "./page.scss";

const localFont = philosopher({
  src: [
    {
      path: '../../public/fonts/philosopher/Philosopher-Regular.ttf',
      weight: '400'
    },
    {
      path: '../../public/fonts/philosopher/Philosopher-Bold.ttf',
      weight: '700'
    }
  ],
  variable: '--font-philosopher'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${localFont.variable} font-sans`}>
        {children}
      </body>
    </html>
  );
}
